apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: krtznu5gz-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: krtznu5gz-go 
  name: krtznu5gz-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: krtznu5gz-go 
